package com.barreragerman.paymentservice.service;

import com.barreragerman.paymentservice.entity.Payment;
import com.barreragerman.paymentservice.repository.PaymentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Random;
import java.util.UUID;

@Service
public class PaymentService {

    @Autowired
    private PaymentRepository paymentRepository;

    public Payment doPayment(Payment payment){
        payment.setPaymentStatus(paymentProcessing());
        //here we set the Id of the transaction only when we send the payment status, it is autogenerated
        payment.setTransactionId(UUID.randomUUID().toString());
        return paymentRepository.save(payment);
    }
    public String paymentProcessing(){
        //api shoould be 3er party payment (paypal,...paytm..anyone)
        //here using the random class we test the succes or failure of the call
        return new Random().nextBoolean()?"success":"false";
    }
}
