package com.barreragerman.paymentservice.service;

import com.barreragerman.paymentservice.entity.Payment;
import com.barreragerman.paymentservice.repository.PaymentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
public class PaymentService {

    @Autowired
    private PaymentRepository paymentRepository;

    public Payment doPayment(Payment payment){
        //here we set the Id of the transaction only when we send the payment status, it is autogenerated
        payment.setTransactionId(UUID.randomUUID().toString());
        return paymentRepository.save(payment);
    }
}
